name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        include:
          - arch: arm64
            os: ubuntu-latest
            runs-on: ubunut-latest-arm64
          - arch: amd64
            os: ubuntu-latest
            runs-on: ubunut-latest-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.1
    
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse-dev libfuse3-dev gcc

      - name: Build
        run: go build -o gittyfs-${{ matrix.arch }} cmd/main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gittyfs-${{ matrix.arch }}
          path: gittyfs-${{ matrix.arch }}

