name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.1
    
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse-dev libfuse3-dev gcc
          sudo apt-get install -y musl-dev musl-tools

      - name: Build amd64
        if: matrix.platform == 'linux/amd64'
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o gittyfs-amd64 cmd/main.go

      - name: Build arm64
        if: matrix.platform == 'linux/arm64'
        run: CGO_ENABLED=1 CC=musl-gcc GOOS=linux GOARCH=arm64 go build -o gittyfs-arm64 cmd/main.go

      - name: Upload Artifact
        if: matrix.platform == 'linux/amd64'
        uses: actions/upload-artifact@v4
        with:
          name: gittyfs-amd64
          path: gittyfs-amd64

      - name: Upload arm64 Artifact
        if: matrix.platform == 'linux/arm64'
        uses: actions/upload-artifact@v4
        with:
          name: gittyfs-arm64
          path: gittyfs-arm64
